import { randomInt } from '../lib/random'
import { createToolPage } from '../shell/createToolPage'

const choices=[['rock','✊'],['paper','✋'],['scissors','✌️']] as const
export function renderRps(root:HTMLElement){
  document.title='Rock paper scissors — Shuffleworks';let selected='rock';let wins=0,losses=0,draws=0
  const page=createToolPage(root,{id:'rps',index:'07',eyebrow:'The classic decider',title:'Rock. Paper.<br><em>Scissors.</em>',accent:'#67e8c3',intro:'Choose your move, then throw against the machine.',controls:`<fieldset class="rps-choices"><legend>Your move</legend>${choices.map(([id,icon])=>`<button data-choice="${id}" aria-pressed="${id==='rock'}"><i>${icon}</i><span>${id}</span></button>`).join('')}</fieldset><button class="tool-action" data-throw>Throw</button>`,stage:`<div class="rps-arena"><article><span>You</span><b data-player>✊</b></article><i>VS</i><article><span>Machine</span><b data-machine>?</b></article></div><div class="tool-outcome" data-rps-result><span>Score · 0–0–0</span><b>Choose your move.</b></div>`})
  const player=root.querySelector<HTMLElement>('[data-player]')!,machine=root.querySelector<HTMLElement>('[data-machine]')!,result=root.querySelector<HTMLElement>('[data-rps-result]')!
  root.querySelectorAll<HTMLButtonElement>('[data-choice]').forEach(button=>button.addEventListener('click',()=>{selected=button.dataset.choice!;root.querySelectorAll('[data-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));player.textContent=choices.find(c=>c[0]===selected)![1]}))
  root.querySelector('[data-throw]')!.addEventListener('click',()=>{const opponent=choices[randomInt(3)][0];machine.textContent='?';root.querySelector('.rps-arena')!.classList.remove('is-throwing');void (root.querySelector('.rps-arena') as HTMLElement).offsetWidth;root.querySelector('.rps-arena')!.classList.add('is-throwing');window.setTimeout(()=>{machine.textContent=choices.find(c=>c[0]===opponent)![1];const diff=(choices.findIndex(c=>c[0]===selected)-choices.findIndex(c=>c[0]===opponent)+3)%3;const verdict=diff===0?'Draw':diff===1?'You win':'Machine wins';if(diff===0)draws++;else if(diff===1)wins++;else losses++;result.innerHTML=`<span>Score · ${wins}–${losses}–${draws}</span><b>${verdict}</b>`;page.announcement.textContent=`${selected} versus ${opponent}. ${verdict}.`},850)})
}
